language: node_js
node_js:
  - "18"

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_success:
  - docker build -t docker-react .
